version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - tododb:/var/lib/postgresql/data
    user: "999:999"
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/todo
    ports:
      - "3001:3001"
    depends_on:
      - db
volumes:
  tododb: